site_name: HomeLab & Cloud
theme:
  name: material
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: deep orange
      accent: deep orange
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode    
      primary: teal
      accent: purple

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: French
      link: /fr/
      lang: fr
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ammaar-e

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/Ammaar-e"  target="_blank" rel="noopener">Ammaar Bedasso</a>

repo_url: https://github.com/Ammaar-e/mkdocs
theme:
  icon:
    repo: fontawesome/brands/git-alt 
    
